services:
  postgres:
    image: postgres
    container_name: ticket_bounty_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_bounty
    ports:
      - '5432:5432'
    volumes:
      - ticket_bounty_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d ticket_bounty']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  ticket_bounty_data:
